// Generated by oxidx_codegen at 2026-01-09 20:33:38
// View: LoginScreen

use oxidx_core::{OxidXComponent, OxidXContext, Rect, Vec2, Renderer, Spacing};
use oxidx_core::layout::StackAlignment;
use oxidx_core::events::OxidXEvent;
use oxidx_std::{Button, Chart, Input, Label, VStack};

/// Generated view struct
pub struct LoginScreen {
    
    root: VStack,
}

impl LoginScreen {
    /// Creates a new instance of the view
    pub fn new() -> Self {
        let mut v_stack_1 = VStack::new();
        v_stack_1.set_spacing(Spacing { gap: 20.0, padding: 0.0 });
        let mut label_2 = Label::new("Welcome Back");
        let mut input_3 = Input::new("Username");
        let mut chart_4 = Chart::new();
        let mut button_5 = Button::new().label("Sign In");
        button_5 = button_5.variant(ButtonVariant::primary);

        v_stack_1.add_child(Box::new(label_2));
        v_stack_1.add_child(Box::new(input_3));
        v_stack_1.add_child(Box::new(chart_4));
        v_stack_1.add_child(Box::new(button_5));

        Self {
            
            root: v_stack_1,
        }
    }

    /// Returns a reference to the root component
    pub fn root(&self) -> &VStack {
        &self.root
    }

    /// Returns a mutable reference to the root component  
    pub fn root_mut(&mut self) -> &mut VStack {
        &mut self.root
    }
}

impl OxidXComponent for LoginScreen {
    fn update(&mut self, delta_time: f32) {
        self.root.update(delta_time);
    }

    fn layout(&mut self, available: Rect) -> Vec2 {
        self.root.layout(available)
    }

    fn render(&self, renderer: &mut Renderer) {
        self.root.render(renderer);
    }

    fn on_event(&mut self, event: &OxidXEvent, ctx: &mut OxidXContext) -> bool {
        self.root.on_event(event, ctx)
    }

    fn on_keyboard_input(&mut self, event: &OxidXEvent, ctx: &mut OxidXContext) {
        self.root.on_keyboard_input(event, ctx);
    }

    fn bounds(&self) -> Rect {
        self.root.bounds()
    }

    fn set_position(&mut self, x: f32, y: f32) {
        self.root.set_position(x, y);
    }

    fn set_size(&mut self, width: f32, height: f32) {
        self.root.set_size(width, height);
    }
}

// (Preview window launched)