// Generated by oxidx_codegen at 2026-01-05 22:23:24
// Schema: grid_test

use oxidx_core::{run_with_config, AppConfig, Color, OxidXComponent, OxidXContext, Rect, Vec2, Spacing};
use oxidx_core::layout::StackAlignment;
use oxidx_std::prelude::*;

pub fn main() {
    let mut vstack_1 = VStack::new();
    vstack_1.set_size(800.0, 600.0);
    vstack_1.set_spacing(Spacing::new(0.0, 10.0));
    let mut grid_2 = Grid::new("my_grid");
    grid_2.set_size(700.0, 400.0);
    grid_2 = grid_2.header_rows(2);
    grid_2 = grid_2.with_id("my_grid");
    grid_2.add_column(Column::new("col_0", "ID").width(100.0));
    grid_2.add_column(Column::new("col_1", "Name").width(100.0));
    grid_2.add_column(Column::new("col_2", "Status").width(100.0));
    grid_2.add_row(Row::new("row_0").cell("col_0", "Cell 0-0").cell("col_1", "Cell 0-1").cell("col_2", "Cell 0-2"));
    grid_2.add_row(Row::new("row_1").cell("col_0", "Cell 1-0").cell("col_1", "Cell 1-1").cell("col_2", "Cell 1-2"));
    grid_2.add_row(Row::new("row_2").cell("col_0", "Cell 2-0").cell("col_1", "Cell 2-1").cell("col_2", "Cell 2-2"));
    grid_2.add_row(Row::new("row_3").cell("col_0", "Cell 3-0").cell("col_1", "Cell 3-1").cell("col_2", "Cell 3-2"));
    grid_2.add_row(Row::new("row_4").cell("col_0", "Cell 4-0").cell("col_1", "Cell 4-1").cell("col_2", "Cell 4-2"));
    grid_2.add_row(Row::new("row_5").cell("col_0", "Cell 5-0").cell("col_1", "Cell 5-1").cell("col_2", "Cell 5-2"));
    grid_2.add_row(Row::new("row_6").cell("col_0", "Cell 6-0").cell("col_1", "Cell 6-1").cell("col_2", "Cell 6-2"));
    grid_2.add_row(Row::new("row_7").cell("col_0", "Cell 7-0").cell("col_1", "Cell 7-1").cell("col_2", "Cell 7-2"));
    grid_2.add_row(Row::new("row_8").cell("col_0", "Cell 8-0").cell("col_1", "Cell 8-1").cell("col_2", "Cell 8-2"));
    grid_2.add_row(Row::new("row_9").cell("col_0", "Cell 9-0").cell("col_1", "Cell 9-1").cell("col_2", "Cell 9-2"));
    vstack_1.add_child(Box::new(grid_2));
    
    run_with_config(
        vstack_1,
        AppConfig::new("grid_test").with_size(800, 600)
    );
}
